import type { Metadata } from 'next'
import { Nunito, Nunito_Sans } from 'next/font/google'
import './globals.css'
import { Header } from '@/components/Header'
import { Footer } from '@/components/Footer'

const nunito = Nunito({
  variable: '--font-nunito',
  subsets: ['latin'],
  display: 'swap',
  weight: ['200', '400', '700'],
})

const nunitoSans = Nunito_Sans({
  variable: '--font-nunito-sans',
  subsets: ['latin'],
  display: 'swap',
  weight: ['200', '400', '700'],
})

export const metadata: Metadata = {
  title: 'Biblia Quiz',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='es'>
      <body className={`${nunito.variable} ${nunitoSans.variable} font-sans antialiased`}>
        <Header />
        <div className='stars'></div>
        <div className='twinkling'></div>
        <main className='container mx-auto px-4 py-8'>{children}</main>
        <Footer />
      </body>
    </html>
  )
}
